user:
  db:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://wangxingdi.com:3306
    name: mysql
    setting: useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false

spring:
  datasource:
    driver-class-name: ${user.db.driver}
    url: ${user.db.url}/${user.db.name}?${user.db.setting}
    type: com.zaxxer.hikari.HikariDataSource
    # hikari
    hikari:
      #????
      pool-name: HikariCP
      #???????:q
      minimum-idle: 5
      # ?????????????10??
      idle-timeout: 600000
      # ????????????10
      maximum-pool-size: 10
      # ?????????????????????,????true
      auto-commit: true
      # ??????????????????0???????????30??
      max-lifetime: 1800000
      # ?????????,??30?
      connection-timeout: 30000
      # ????query
      connection-test-query: SELECT 1
