user:
  db:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://your-ip:3306
    name: mysql
    setting: useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false

spring:
  datasource:
    driver-class-name: ${user.db.driver}
    url: ${user.db.url}/${user.db.name}?${user.db.setting}
    type: com.zaxxer.hikari.HikariDataSource
    # hikari
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
